platform:ios ,'8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
#link_with  'SDDouYu'

target 'SDDouYu' do
    pod 'MJRefresh', '~> 3.0.0'
    pod 'Masonry'         #约束
    pod 'DateTools'
    pod 'MJExtension'
    pod 'ReactiveCocoa','~>4.0.4-alpha-1'
    pod 'KMCGeigerCounter', '~> 0.2.2' #测试滑动流畅度
    pod 'CocoaLumberjack', '~> 2.3.0' #日志分析工具
    pod 'BlocksKit', '~> 2.2.5'
    pod 'SDWebImage'
    pod 'SDBannerView'
    pod 'SVProgressHUD'
    pod 'pop', '~> 1.0'
    pod 'YYKit'
    #OC
    pod 'AFNetworking', '~>3.0.0'
    #swift
    #pod 'Alamofire'
    pod 'HYBImageCliped', '~> 2.0.0' #圆角处理
end


