platform:ios ,'8.0'
use_frameworks!

target 'SDDouYu' do



pod 'MJRefresh', '~> 3.0.0'
pod 'Masonry'         #约束
pod 'DateTools'
pod 'MJExtension'
pod 'ReactiveCocoa','~>4.0.4-alpha-1'
pod 'KMCGeigerCounter', '~> 0.2.2' #测试滑动流畅度
pod 'CocoaLumberjack', '~> 2.3.0' #日志分析工具
pod 'SDWebImage'
pod 'SDBannerView'
pod 'SVProgressHUD'
pod 'AFNetworking' #OC
#pod 'Alamofire'  #swift
pod 'pop', '~> 1.0'


link_with  ['SDDouYu', 'SDDouYuTests']
end
